### ISSUE TITLE
(nghttpx) Worker process dead with segfault

### ISSUE THREAD

**Issue by JinyoungKim0219** [nghttp2/nghttp2#1208]
Dear @tatsuhiro-t ,

I'm trying to use nghttpx in i.MX8(with aarch64 linux), and I'm having crash that always occurs.
I'm building nghttpx with yocto, and here's recipe:

```
SUMMARY = "the implementation of nghttp2"
SECTION = "base"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "..."

DEPENDS = "pkgconfig openssl libev zlib c-ares libxml2"
FILESEXTRAPATHS_prepend := "${THISDIR}/${PN}:"

SRCREV = "${AUTOREV}"
SRC_URI = "git://github.com/nghttp2/${BPN}.git;protocol=https"
S = "${WORKDIR}/git"

inherit cmake lib_package gitpkgv debug-feature

EXTRA_OECMAKE += "-DCMAKE_BUILD_TYPE=Debug"

PACKAGES_remove += "${PN}-bin"
FILES_${PN} += "${bindir}/nghttp2"
FILES_${PN}-dev += "${libdir}/cmake"

BBCLASSEXTEND = "nativesdk"
```

And I make service file to run nghttpx such as:
`ExecStart=/usr/bin/nghttpx -b'localhost,8080' -f'*,8443;no-tls' -LINFO`

And the nghttpx log shows that initial launching is success.
> Aug 16 00:29:51 nghttpx[2198]: 2018-08-16T00:29:51.919Z 2198 2198 96f1ffad INFO (/usr/src/debug/nghttp2/1.32.0-r0/git/src/shrpx_config.cc:3838) Resolving backend address
Aug 16 00:29:51 nghttpx[2198]: 2018-08-16T00:29:51.919Z 2198 2198 96f1ffad INFO (/usr/src/debug/nghttp2/1.32.0-r0/git/src/shrpx_config.cc:3848) Host-path pattern: group 0: '/'
Aug 16 00:29:51 nghttpx[2198]: 2018-08-16T00:29:51.920Z 2198 2198 96f1ffad INFO (/usr/src/debug/nghttp2/1.32.0-r0/git/src/shrpx_config.cc:3851) group 0 -> localhost:8080, proto=http/1.1
Aug 16 00:29:51 nghttpx[2198]: 2018-08-16T00:29:51.920Z 2198 2198 96f1ffad INFO (/usr/src/debug/nghttp2/1.32.0-r0/git/src/shrpx_config.cc:3867) Catch-all pattern is group 0
Aug 16 00:29:51 nghttpx[2198]: 2018-08-16T00:29:51.927Z 2198 2198 96f1ffad INFO (/usr/src/debug/nghttp2/1.32.0-r0/git/src/shrpx_config.cc:4000) Address resolution for localhost succeeded: ::1
Aug 16 00:29:51 nghttpx[2198]: 2018-08-16T00:29:51.927Z 2198 2198 96f1ffad INFO (/usr/src/debug/nghttp2/1.32.0-r0/git/src/shrpx_config.cc:3917) Resolved backend address: localhost:8080 -> [::1]:8080
Aug 16 00:29:51 nghttpx[2198]: 2018-08-16T00:29:51.927Z 2198 2198 96f1ffad NOTICE (/usr/src/debug/nghttp2/1.32.0-r0/git/src/shrpx.cc:859) Listening on 0.0.0.0:8443
Aug 16 00:29:51 nghttpx[2198]: 2018-08-16T00:29:51.927Z 2198 2198 96f1ffad NOTICE (/usr/src/debug/nghttp2/1.32.0-r0/git/src/shrpx.cc:859) Listening on [::]:8443
Aug 16 00:29:51 nghttpx[2198]: 2018-08-16T00:29:51.928Z 2198 2198 96f1ffad NOTICE (/usr/src/debug/nghttp2/1.32.0-r0/git/src/shrpx.cc:1302) Worker process [2210] spawned
Aug 16 00:29:51 nghttpx[2198]: 2018-08-16T00:29:51.935Z 2198 2198 96f1ffad INFO (/usr/src/debug/nghttp2/1.32.0-r0/git/src/shrpx_worker.cc:274) number of http/1.1 backend: 1, number of h2 backend: 0
Aug 16 00:29:51 nghttpx[2198]: 2018-08-16T00:29:51.935Z 2198 2198 96f1ffad NOTICE (/usr/src/debug/nghttp2/1.32.0-r0/git/src/shrpx_connection_handler.cc:311) [LISTEN:0xffffe0fa80b0] Created worker thread #0
Aug 16 00:29:51 nghttpx[2198]: 2018-08-16T00:29:51.935Z 2198 2198 96f1ffad INFO (/usr/src/debug/nghttp2/1.32.0-r0/git/src/shrpx_worker_process.cc:557) Entering event loop

And it goes down when I type command such as 'curl http://localhost:8443',
> Aug 16 00:32:36 nghttpx[2198]: 2018-08-16T00:32:36.965Z 2198 2198 96f1ffad INFO (/usr/src/debug/nghttp2/1.32.0-r0/git/src/shrpx_connection_handler.cc:373) [LISTEN:0xffffe0fa80b0] Accepted connection from ::1, fd=11
Aug 16 00:32:36 nghttpx[2198]: 2018-08-16T00:32:36.965Z 2198 2198 96f1ffad INFO (/usr/src/debug/nghttp2/1.32.0-r0/git/src/shrpx_connection_handler.cc:417) Dispatch connection to worker #0
Aug 16 00:32:36 nghttpx[2198]: 2018-08-16T00:32:36.965Z 2198 2210 b50957b2 INFO (/usr/src/debug/nghttp2/1.32.0-r0/git/src/shrpx_worker.cc:368) [WORKER:0x193af340] WorkerEvent: client_fd=11, addrlen=28
Aug 16 00:32:36 nghttpx[2198]: 2018-08-16T00:32:36.965Z 2198 2210 b50957b2 INFO (/usr/src/debug/nghttp2/1.32.0-r0/git/src/shrpx_worker.cc:395) [WORKER:0x193af340] CLIENT_HANDLER:0xffff74000d50 created
Aug 16 00:32:36 nghttpx[2198]: 2018-08-16T00:32:36.966Z 2198 2210 b50957b2 INFO (/usr/src/debug/nghttp2/1.32.0-r0/git/src/shrpx_client_handler.cc:340) [CLIENT_HANDLER:0xffff74000d50] This is HTTP/1.1 connection, but may be upgraded to HTTP/2 later.
Aug 16 00:32:37 nghttpx[2198]: 2018-08-16T00:32:37.583Z 2198 2198 96f1ffad NOTICE (/usr/src/debug/nghttp2/1.32.0-r0/git/src/shrpx_log.cc:697) Worker process: [2210] exited abnormally with status 8b; exit status 0; signal Segmentation fault(11)
Aug 16 00:32:37 nghttpx[2198]: 2018-08-16T00:32:37.583Z 2198 2198 96f1ffad NOTICE (/usr/src/debug/nghttp2/1.32.0-r0/git/src/shrpx.cc:4210) Shutdown momentarily

I find out that it is related with epoll thing.

> *** *** *** 2018-08-16-00-32-36 *** *** ***
> Crash: pid=2210 uid=0 gid=0 tid=2212 signal=11(Segmentation fault) fault_addr=0x0xffff79c85b38
> 
> ----- Pid: 2210, Tid: 2210, comm: nghttpx, cmdline: /usr/bin/nghttpx -----
> 
> Register:
> x0 : 0xFFFFFFFFFFFFFFFC  x1 : 0x00000000193AD120  x2 : 0x0000000000000040  x3 : 0x000000000000E95F
> x4 : 0x0000000000000000  x5 : 0x0000000000000008  x6 : 0x0000000000000000  x7 : 0x0000000000000000
> x8 : 0x0000000000000016  x9 : 0x003B9ACA00000000  x10: 0x00000000000000A9  x11: 0x000000001CD7266D
> x12: 0x0000000000000018  x13: 0x000000005B74C624  x14: 0x0039387000000000  x15: 0x0000576683000000
> ip0: 0x0000FFFF79F5BC40  ip1: 0x0000FFFF799AEA88  x18: 0x0000000000000000  x19: 0x000000000000E95F
> x20: 0x0000000000000040  x21: 0x0000000000000006  x22: 0x0000000000000000  x23: 0x00000000193AD120
> x24: 0x0000FFFFE0FA8318  x25: 0x0000FFFF79F5C4E0  x26: 0x0000FFFFE0FA96E8  x27: 0x00000000004B7450
> x28: 0x0000000000000000  fp : 0x0000FFFFE0FA6E50  lr : 0x0000FFFF799AED04  sp : 0x0000FFFFE0FA6E50
> pc : 0x0000FFFF799AED04
> 
> Backtrace :
> #0  [<0xffff799aed04>] (epoll_pwait + 0x9c) [/lib/libc-2.24.so + 0xc7d04]
>         /usr/src/debug/glibc/2.24-r0/git/sysdeps/unix/sysv/linux/epoll_pwait.c:42 (discriminator 2)
> 
> ----- Pid: 2210, Tid: 2212, comm: nghttpx, cmdline: /usr/bin/nghttpx -----
> 
> Register:
> x0 : 0x000000000000000F  x1 : 0x0000FFFF796DE0A4  x2 : 0x0000000000000001  x3 : 0x0000FFFF796DE00C
> x4 : 0x0000FFFF796E02E8  x5 : 0x0000FFFF796E01E0  x6 : 0x0000FFFF796E08D0  x7 : 0x0000000000000000
> x8 : 0x000000000000003F  x9 : 0x003B9ACA00000000  x10: 0x0101010101010101  x11: 0x0000000039A7BDA7
> x12: 0x0000000000000018  x13: 0x000000005B74C624  x14: 0x0000000000000000  x15: 0x00000000000000E2
> ip0: 0x0000000000000000  ip1: 0x0000FFFF7A006A50  x18: 0x0000000000000000  x19: 0x0000000000000018
> x20: 0x0000FFFF79FF6520  x21: 0x000000000000000F  x22: 0x0000FFFF79FF6000  x23: 0x0000FFFF79FF6550
> x24: 0x0000FFFF796DE0A4  x25: 0x0000FFFF796DE0A8  x26: 0x0000FFFF796DE130  x27: 0x0000FFFF796E01E0
> x28: 0x0000FFFFE0FA8210  fp : 0x0000FFFF796DE050  lr : 0x0000FFFF79D6EF18  sp : 0x0000FFFF796DE010
> pc : 0x0000FFFF79D6EF18
> 
> Backtrace :
> #0  [<0xffff79d6ef18>] (read + 0x28) [/lib/libpthread-2.24.so + 0x10f18]
>         /usr/src/debug/glibc/2.24-r0/git/nptl/../sysdeps/unix/syscall-template.S:86
> #1  [<0xffff79ff6294>] (request_backtrace(int, siginfo_t*) + 0x1a4) [/usr/lib/libtigris_client.so.0.0.0 + 0x1294]
> #2  [<0xffff79ff6404>] (request_backtrace(int, siginfo_t*) + 0x314) [/usr/lib/libtigris_client.so.0.0.0 + 0x1404]
> #3  [<0xffff7a0316c0>] (<Unknown> + 0x0) [[vdso] + 0x6c0]
> ------ Cut Out Signal Frame, Actual backtrace is in below ------
> #4  [<0xffff79c85b38>] (<Unknown> + 0x0) [/usr/lib/libstdc++.so.6.0.22 + 0x7b38]

This issue is reproduced every time. Is it related with libev? Or should I put some arguments for building nghttpx?
Please help me solving this issue.

Best regards,

**Comment by tatsuhiro-t** [comment]
Could you share the HTTP request you make?  It looks like nghttpx exited before reading any HTTP request.

**Comment by tatsuhiro-t** [comment]
No, I haven't saw this kind of crash.
Valgrind shows several errors in epoll_ctl and epoll_pwait.
Is yocto linux so special regarding epoll stuff?

**Comment by JinyoungKim0219** [comment]
Dear @tatsuhiro-t ,
It was not the problem with epoll thing.
With gdb, I get following backtrace logs:

> #0  0x0000ffffa6c43b38 in construction vtable for std::istream-in-std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > () from /usr/lib/libstdc++.so.6
> #1  0x00000000004fce70 in std::function<int (shrpx::ClientHandler&)>::operator()(shrpx::ClientHandler&) const (__args#0=..., this=0x11e72578) at /usr/include/c++/6.2.0/functional:2136
> #2  shrpx::ClientHandler::on_read (this=this@entry=0x11e72200) at /usr/src/debug/nghttp2/1.32.0-r0/git/src/shrpx_client_handler.cc:626
> #3  0x00000000004fdba4 in shrpx::ClientHandler::upstream_http1_connhd_read (this=0x11e72200) at /usr/src/debug/nghttp2/1.32.0-r0/git/src/shrpx_client_handler.cc:371
> #4  0x00000000004fce70 in std::function<int (shrpx::ClientHandler&)>::operator()(shrpx::ClientHandler&) const (__args#0=..., this=0x11e72578) at /usr/include/c++/6.2.0/functional:2136
> #5  shrpx::ClientHandler::on_read (this=this@entry=0x11e72200) at /usr/src/debug/nghttp2/1.32.0-r0/git/src/shrpx_client_handler.cc:626
> #6  0x00000000004fd0f4 in shrpx::ClientHandler::read_clear (this=0x11e72200) at /usr/src/debug/nghttp2/1.32.0-r0/git/src/shrpx_client_handler.cc:116
> #7  0x00000000004fccfc in std::function<int (shrpx::ClientHandler&)>::operator()(shrpx::ClientHandler&) const (__args#0=..., this=0x11e72538) at /usr/include/c++/6.2.0/functional:2136
> #8  shrpx::ClientHandler::do_read (this=0x11e72200) at /usr/src/debug/nghttp2/1.32.0-r0/git/src/shrpx_client_handler.cc:621
> #9  shrpx::(anonymous namespace)::readcb (loop=<optimized out>, w=<optimized out>, revents=<optimized out>) at /usr/src/debug/nghttp2/1.32.0-r0/git/src/shrpx_client_handler.cc:92
> #10 0x0000ffffa6efe49c in ev_invoke_pending (loop=0xffffa6f155c0 <default_loop_struct>) at /usr/src/debug/libev/4.24-r0/libev-4.24/ev.c:3317


I put following line in nghttp2 recipe, and it solves problem
`CXXFLAGS += "-D_GLIBCXX_USE_CXX11_ABI=0"`

I'm not sure, but it might be a problem with conversion between std::string and std::__cxx11::string with other third-party libraries.
I think it would be better for other person to leave this comment who might have same problem with me.

Best regards,
