### ISSUE TITLE
Compression error

### ISSUE THREAD

**Issue by ranjithpp** [nghttp2/nghttp2#1302]
When is the compression_error generate in server ?
While using h2load server application which is built using nghttp2 sends compression error for the second request and send goaway.
While using other tool like jmeter this issue is not observed. I have seen other questions asked is the compression of header is by default, if it is by default do need to check any flags?

while sending 1 message success response is received

]# h2load "http://localhost:16800?pei=12345678901234&supi=im                                                                      si-12345678901234" -n 1
starting benchmark...
spawning thread #0: 1 total client(s). 1 total requests
Application protocol: h2c
progress: 100% done

finished in 4.34ms, 230.20 req/s, 7.64KB/s
requests: 1 total, 1 started, 1 done, 1 succeeded, 0 failed, 0 errored, 0 timeou                                                                      t
status codes: 1 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 34B (34) total, 1B (1) headers (space savings 90.00%), 0B (0) data
                     min         max         mean         sd        +/- sd
time for request:     3.53ms      3.53ms      3.53ms         0us   100.00%
time for connect:      392us       392us       392us         0us   100.00%
time to 1st byte:     4.00ms      4.00ms      4.00ms         0us   100.00%
req/s           :     243.43      243.43      243.43        0.00   100.00%

while sending couner > 1,  it is stuck below point,
h2load "http://localhost:16800?pei=12345678901234&supi=imsi-12345678901234" -n 2
starting benchmark...
spawning thread #0: 1 total client(s). 2 total requests
Application protocol: h2c
gdb output shows a compression error in 

#0  nghttp2_hd_inflate_hd_nv (inflater=inflater@entry=0x2aaad806a980,
    nv_out=nv_out@entry=0x2aaacfb6e5e0,
    inflate_flags=inflate_flags@entry=0x2aaacfb6e5cc,
    in=in@entry=0x2aaad8007d33 "\004\241c\374\254\246\200\"e\246\334u\347\300\021\062\327\302-\254\320\032\224\031`\211\226\233qן", inlen=inlen@entry=69,
    in_final=in_final@entry=1) at nghttp2_hd.c:1872
#1  0x00002aaab4656f72 in inflate_header_block (call_header_cb=1, final=1,
    inlen=69,
    in=0x2aaad8007d33 "\004\241c\374\254\246\200\"e\246\334u\347\300\021\062\327\302-\254\320\032\224\031`\211\226\233qן", readlen_ptr=<synthetic pointer>,
    frame=0x2aaad806a438, session=0x2aaad806a2a0) at nghttp2_session.c:3587
#2  nghttp2_session_mem_recv (session=session@entry=0x2aaad806a2a0,
    in=0x2aaad8007d33 "\004\241c\374\254\246\200\"e\246\334u\347\300\021\062\327\302-\254\320\032\224\031`\211\226\233qן", inlen=inlen@entry=136)
    at nghttp2_session.c:6177
#3  0x000000000040649c in session_recv (len=136, data=<optimized out>,
    session_p=0x2aaad806a2a0) at httpProtocol.c:59

**Comment by tatsuhiro-t** [comment]
Which server application did emit this compression error?

**Comment by ranjithpp** [comment]
Thanks for response. I took the sample code provided in nghttp2 (https://nghttp2.org/documentation/tutorial-server.html) and made use it in my application.

when i was testing using h2load, issue observed. 
i used nghttpd and h2load, that time it is working fine.
when used jmeter as a test tool client it is working fine as well
Attached screenshot captured in wireshark
![image](https://user-images.githubusercontent.com/47220450/52320821-6fbf9c00-29f7-11e9-999b-c218882f2bf3.png)
