### ISSUE TITLE
Crash observed at nghttp2_pq_top due to empty buffer and non-zero length

### ISSUE THREAD

**Issue by RekhaBalasu** [nghttp2/nghttp2#1357]
Hello everyone!

During our  application load tests involving the nghttp2 (version 1.36) , we are observing a crash in the following scenario: 
"About 20 peers establish connection with our application, and requests are being sent. When we disconnect the peer one by one abruptly during ongoing request processing, a crash is observed"

Here is the trace of the crash:
#0  0x0000000000000000 in ?? ()
#1  0x00002aaab19fd04b in sdfdb_criticalSignalAction (signo=11, info_p=0x7fffffffd130, ulctx_p=<optimized out>)
    at sdfdb_sighandler.c:275
#2  <signal handler called>
#3  0x00002aaaab105fea in nghttp2_pq_top (pq=0xf572b38) at nghttp2_pq.c:94
#4  0x00002aaaab109449 in nghttp2_stream_next_outbound_item (stream=<optimized out>, stream@entry=0xf572b20)
    at nghttp2_stream.c:940
#5  0x00002aaaab10b75c in nghttp2_session_pop_next_ob_item (session=session@entry=0xf572b00)
    at nghttp2_session.c:2369
#6  0x00002aaaab10e638 in nghttp2_session_mem_send_internal (session=session@entry=0xf572b00,
    data_ptr=data_ptr@entry=0x7fffffffdd78, fast_cb=fast_cb@entry=0) at nghttp2_session.c:2912
#7  0x00002aaaab10f54a in nghttp2_session_send (session=0xf572b00) at nghttp2_session.c:3239
#8  0x00002aaaaaef96ec in http2ApiSend (session=<optimized out>) at http2Api.c:96
......<application specific calls>

On examining the frame #3 contents, it can be seen that the value of pq->length is 1, where as the buffer q is having NULL. Details as follows:
(gdb) frame 3
#3  0x00002aaaab105fea in nghttp2_pq_top (pq=0xf572b38) at nghttp2_pq.c:94
94      nghttp2_pq.c: No such file or directory.
(gdb) p *pq
$1 = {
  q = 0x0,
  mem = 0xf573388,
  length = 1,
  capacity = 4,
  less = 0x2aaaab1086d0 <stream_less>
}

On examining the code of nghttp2_pq_top method, it can be seen that there is a boundary length check. however, in our scenario, the crash is being caused as a result of the else condition:

 nghttp2_pq_entry *nghttp2_pq_top(nghttp2_pq *pq) {
  if (pq->length == 0) {
    return NULL;
  } else {
    return pq->q[0];
  }
}

Appreciate your help here. 
Thanks in advance!

**Comment by vgmahajanshetty** [comment]
Hi,

I am also seeing similar issue "https://github.com/nghttp2/nghttp2/issues/1432".
Kindly let me know if you were you able to figure out what is the issue? Anything wrong in the application code?

Thank you.
