### ISSUE TITLE
Double free of frame->nva?

### ISSUE THREAD

**Issue by mdsiebler** [nghttp2/nghttp2#1893]
Hi we are encountering a crash in our application when using nghttp library. This only happens when the client sends the Expect: 100-continue header in the request.

In our code; when we see this header; we first call nghttp2_submit_headers and then later nghttp2_session_send to send the 100 response code back. Then later we call nghttp2_session_send again to send the rest of the response.
When testing we found an intermittent crash.
Using the google AddressSanitizer tool it was reporting a double free: what we see is; removing our code:

the nva is first allocated here:

previously allocated by thread T13 here:
    #0 0x7ffff6ef0ba8 in __interceptor_malloc (/home/matthias/sandboxes/mds-10-5/_build/x86_64/third-party/install/lib64/libasan.so.5+0xefba8)
    #1 0x9e9f982 in nghttp2_nv_array_copy /home/matthias/sandboxes/mds-10-5/_build/x86_64/third-party/nghttp2/nghttp2-1.41.0/lib/nghttp2_frame.c:983
    #2 0x9e9891a in submit_headers_shared_nva /home/matthias/sandboxes/mds-10-5/_build/x86_64/third-party/nghttp2/nghttp2-1.41.0/lib/nghttp2_submit.c:162
    #3 0x9e98b32 in nghttp2_submit_headers /home/matthias/sandboxes/mds-10-5/_build/x86_64/third-party/nghttp2/nghttp2-1.41.0/lib/nghttp2_submit.c:210

then it is freed here:

freed by thread T13 here:
    #0 0x7ffff6ef07e0 in __interceptor_free (/home/matthias/sandboxes/mds-10-5/_build/x86_64/third-party/install/lib64/libasan.so.5+0xef7e0)
    #1 0x9e90274 in active_outbound_item_reset /home/matthias/sandboxes/mds-10-5/_build/x86_64/third-party/nghttp2/nghttp2-1.41.0/lib/nghttp2_session.c:394
    #2 0x9e92720 in session_after_frame_sent2 /home/matthias/sandboxes/mds-10-5/_build/x86_64/third-party/nghttp2/nghttp2-1.41.0/lib/nghttp2_session.c:2851
    #3 0x9e94c92 in nghttp2_session_mem_send_internal /home/matthias/sandboxes/mds-10-5/_build/x86_64/third-party/nghttp2/nghttp2-1.41.0/lib/nghttp2_session.c:3098
    #4 0x9e959dd in nghttp2_session_send /home/matthias/sandboxes/mds-10-5/_build/x86_64/third-party/nghttp2/nghttp2-1.41.0/lib/nghttp2_session.c:3243

but the pointer is not set to null after being freed; and later it is being used again here:

==1774295==ERROR: AddressSanitizer: attempting double-free on 0x60b000bb9780 in thread T15:
    #0 0x7ffff6ef07e0 in __interceptor_free (/home/matthias/sandboxes/mds-10-5/_build/x86_64/third-party/install/lib64/libasan.so.5+0xef7e0)
    #1 0x9e90274 in active_outbound_item_reset /home/matthias/sandboxes/mds-10-5/_build/x86_64/third-party/nghttp2/nghttp2-1.41.0/lib/nghttp2_session.c:394
    #2 0x9e92720 in session_after_frame_sent2 /home/matthias/sandboxes/mds-10-5/_build/x86_64/third-party/nghttp2/nghttp2-1.41.0/lib/nghttp2_session.c:2851
    #3 0x9e94c92 in nghttp2_session_mem_send_internal /home/matthias/sandboxes/mds-10-5/_build/x86_64/third-party/nghttp2/nghttp2-1.41.0/lib/nghttp2_session.c:3098
    #4 0x9e959dd in nghttp2_session_send /home/matthias/sandboxes/mds-10-5/_build/x86_64/third-party/nghttp2/nghttp2-1.41.0/lib/nghttp2_session.c:3243

This is using the nghttp2-1.41.0 library
Is this a known issue? thanks

**Comment by mdsiebler** [comment]
Yes we do thanks, so this has not been seen before?
