### ISSUE TITLE
cross-compilation with --with-mruby flag enabled.

### ISSUE THREAD

**Issue by andrey-eero** [nghttp2/nghttp2#1908]
Does ngthhp2 support cross-compilation with `--with-mruby` flag enabled?

I tried to configure it using:
`./configure --build=x86_64 --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf  --disable-examples --with-mruby --disable-failmalloc`

However I get compilation error:
```
CC    mruby/src/symbol.c -> mruby/build/mrbc/src/symbol.o
CC    mruby/src/variable.c -> mruby/build/mrbc/src/variable.o
CC    mruby/src/version.c -> mruby/build/mrbc/src/version.o
CXX   mruby/build/mrbc/mruby/src/vm-cxx.cxx -> mruby/build/mrbc/mruby/src/vm-cxx.o
CXX   mruby/build/mrbc/mruby/mrbgems/mruby-compiler/core/codegen-cxx.cxx -> mruby/build/mrbc/mruby/mrbgems/mruby-compiler/core/codegen-cxx.o
CXX   mruby/build/mrbc/mruby/mrbgems/mruby-compiler/core/y.tab-cxx.cxx -> mruby/build/mrbc/mruby/mrbgems/mruby-compiler/core/y.tab-cxx.o
AR    mruby/build/mrbc/lib/libmruby_core.a 
ar: creating /work/nghttp2/third-party/mruby/build/mrbc/lib/libmruby_core.a
LD    mruby/build/mrbc/bin/mrbc 
/usr/bin/ld: /work/nghttp2/third-party/mruby/build/mrbc/mrbgems/mruby-bin-mrbc/tools/mrbc/mrbc.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: /work/nghttp2/third-party/mruby/build/mrbc/mrbgems/mruby-bin-mrbc/tools/mrbc/mrbc.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: /work/nghttp2/third-party/mruby/build/mrbc/mrbgems/mruby-bin-mrbc/tools/mrbc/mrbc.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: /work/nghttp2/third-party/mruby/build/mrbc/mrbgems/mruby-bin-mrbc/tools/mrbc/mrbc.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: /work/nghttp2/third-party/mruby/build/mrbc/mrbgems/mruby-bin-mrbc/tools/mrbc/mrbc.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: /work/nghttp2/third-party/mruby/build/mrbc/mrbgems/mruby-bin-mrbc/tools/mrbc/mrbc.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: /work/nghttp2/third-party/mruby/build/mrbc/mrbgems/mruby-bin-mrbc/tools/mrbc/mrbc.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: /work/nghttp2/third-party/mruby/build/mrbc/mrbgems/mruby-bin-mrbc/tools/mrbc/mrbc.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: /work/nghttp2/third-party/mruby/build/mrbc/mrbgems/mruby-bin-mrbc/tools/mrbc/mrbc.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: /work/nghttp2/third-party/mruby/build/mrbc/mrbgems/mruby-bin-mrbc/tools/mrbc/mrbc.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: /work/nghttp2/third-party/mruby/build/mrbc/mrbgems/mruby-bin-mrbc/tools/mrbc/mrbc.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: /work/nghttp2/third-party/mruby/build/mrbc/mrbgems/mruby-bin-mrbc/tools/mrbc/mrbc.o: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
rake aborted!
Command failed with status (1): [g++  -o "/work/nghttp2/third-party/mruby/b...]
/work/nghttp2/third-party/mruby/lib/mruby/build/command.rb:33:in `_run'
/work/nghttp2/third-party/mruby/lib/mruby/build/command.rb:213:in `run'
/work/nghttp2/third-party/mruby/mrbgems/mruby-bin-mrbc/mrbgem.rake:11:in `block (2 levels) in <top (required)>'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => default => all => gensym => /work/nghttp2/third-party/mruby/build/presym => /work/nghttp2/third-party/mruby/build/mrblib/mrblib.pi => /work/nghttp2/third-party/mruby/build/mrblib/mrblib.c => /work/nghttp2/third-party/mruby/build/mrbc/bin/mrbc
(See full trace by running task with --trace)
make[2]: *** [Makefile:1236: mruby] Error 1
make[2]: Leaving directory '/work/nghttp2/third-party'
make[1]: *** [Makefile:566: all-recursive] Error 1
make[1]: Leaving directory '/work/nghttp2'
make: *** [Makefile:475: all] Error 2
```
with cross-compilation enabled mrbc is compiled into target architecture instead of host architecture and can't be linked correctly for host architecture. mruby itself supports cross-compilation but nghttp2 passes to it only info about target architecture.

**Comment by tatsuhiro-t** [comment]
Could you share how to write build_config.rb in order to make cross build work?

**Comment by tatsuhiro-t** [comment]
I managed to do cross build with #1918
Not tested whether the produced binary works on the target platform.
