### ISSUE TITLE
SegFault while loading config after upgrade from 1.57.0 to 1.61.0

### ISSUE THREAD

**Issue by andrey-eero** [nghttp2/nghttp2#2145]
I am using nghttp2 on a embedded device (ARMv7). After upgrading nghttp2 from 1.57.0 to 1.61.0 I started to get SegFault while nghttpx is loading its config file.
Analyze core dump in gdb shows this:

```
Core was generated by `nghttpx --conf=/etc/nghttpx/nghttpx.conf'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x54b8a274 in shrpx::(anonymous namespace)::find_next_node(shrpx::RNode const*, char) ()
The target architecture is set to "auto" (currently "armv7").
(gdb) bt
#0  0x54b8a274 in shrpx::(anonymous namespace)::find_next_node(shrpx::RNode const*, char) ()
#1  0x54b8af58 in shrpx::Router::add_route(nghttp2::StringRef const&, unsigned int, bool) ()
#2  0x54b2e1c0 in shrpx::(anonymous namespace)::parse_mapping(shrpx::Config*, shrpx::DownstreamAddrConfig&, std::map<nghttp2::StringRef, unsigned int, std::less<nghttp2::StringRef>, std::allocator<std::pair<nghttp2::StringRef const, unsigned int> > >&, nghttp2::StringRef const&, nghttp2::StringRef const&) ()
#3  0x54b343b8 in shrpx::parse_config(shrpx::Config*, int, nghttp2::StringRef const&, nghttp2::StringRef const&, std::set<nghttp2::StringRef, std::less<nghttp2::StringRef>, std::allocator<nghttp2::StringRef> >&, std::map<nghttp2::StringRef, unsigned int, std::less<nghttp2::StringRef>, std::allocator<std::pair<nghttp2::StringRef const, unsigned int> > >&) ()
#4  0x54b39294 in shrpx::load_config(shrpx::Config*, char const*, std::set<nghttp2::StringRef, std::less<nghttp2::StringRef>, std::allocator<nghttp2::StringRef> >&, std::map<nghttp2::StringRef, unsigned int, std::less<nghttp2::StringRef>, std::allocator<std::pair<nghttp2::StringRef const, unsigned int> > >&) ()
#5  0x54b15458 in shrpx::(anonymous namespace)::process_options(shrpx::Config*, std::vector<std::pair<nghttp2::StringRef, nghttp2::StringRef>, std::allocator<std::pair<nghttp2::StringRef, nghttp2::StringRef> > >&) [clone .constprop.0] ()
#6  0x54b0d5e8 in shrpx::main(int, char**) ()
#7  0x54b18988 in nghttp2::run_app(std::function<int (int, char**)>, int, char**) ()
#8  0x54b0bef8 in main ()
```

After some experiments I found that SegFault happened while parsing these lines:

```
backend=127.0.0.1,40075;/network.setup.connect.Station/ScanNetworks;proto=h2
backend=127.0.0.1,40075;/network.setup.connect.Station/ConnectBackupNetwork;proto=h2
```
If I comment out any of these lines, nghttpx starts without any problem. on 1.57.0 this config file works without any issue

**Comment by andrey-eero** [comment]
```
# valgrind nghttpx --conf=/etc/nghttpx/nghttpx.conf
==2949== Memcheck, a memory error detector
==2949== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==2949== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==2949== Command: nghttpx --conf=/etc/nghttpx/nghttpx.conf
==2949== 
2024-04-09T17:37:30.172Z 2949 2949 6c27c749 NOTICE (../../nghttp2-1.61.0/src/shrpx.cc:3663) Loading configuration from /etc/nghttpx/nghttpx.conf
==2949== Invalid write of size 4
==2949==    at 0x126B5C: ??? (in /usr/bin/nghttpx)
==2949==    by 0x13E9BF: ??? (in /usr/bin/nghttpx)
==2949==  Address 0x5259260 is 8 bytes after a block of size 1,040 alloc'd
==2949==    at 0x4866BCC: operator new[](unsigned int) (vg_replace_malloc.c:633)
==2949==    by 0x19668F: ??? (in /usr/bin/nghttpx)
==2949==    by 0x19740F: ??? (in /usr/bin/nghttpx)
==2949==    by 0x1340EB: ??? (in /usr/bin/nghttpx)
==2949== 
==2949== Invalid write of size 1
==2949==    at 0x126C08: ??? (in /usr/bin/nghttpx)
==2949==    by 0x13E9BF: ??? (in /usr/bin/nghttpx)
==2949==  Address 0x5259264 is 12 bytes after a block of size 1,040 alloc'd
==2949==    at 0x4866BCC: operator new[](unsigned int) (vg_replace_malloc.c:633)
==2949==    by 0x19668F: ??? (in /usr/bin/nghttpx)
==2949==    by 0x19740F: ??? (in /usr/bin/nghttpx)
==2949==    by 0x1340EB: ??? (in /usr/bin/nghttpx)
==2949== 

valgrind: m_mallocfree.c:303 (get_bszB_as_is): Assertion 'bszB_lo == bszB_hi' failed.
valgrind: Heap block lo/hi size mismatch: lo = 1088, hi = 1073.
This is probably caused by your program erroneously writing past the
end of a heap block and corrupting heap metadata.  If you fix any
invalid writes reported by Memcheck, this assertion failure will
probably go away.  Please try that before reporting this as a bug.


host stacktrace:
==2949==    at 0x5803C500: ??? (in /usr/libexec/valgrind/memcheck-arm-linux)

sched status:
  running_tid=1

Thread 1: status = VgTs_Runnable (lwpid 2949)
==2949==    at 0x126C38: ??? (in /usr/bin/nghttpx)
==2949==    by 0x13E9BF: ??? (in /usr/bin/nghttpx)
client stack range: [0x7DC44000 0x7DC48FFF] client SP: 0x7DC46D40
valgrind stack range: [0x421D2000 0x422D1FFF] top usage: 25400 of 1048576


```

**Comment by tatsuhiro-t** [comment]
nghttpx BlockAllocator has alignment issues on 32 bits systems.  #2146 fixes it.  Could you try the patch?

**Comment by andrey-eero** [comment]
Yes. This patch fixed the issue. Thank you for the quick fix!
Closing the ticket.
