### ISSUE TITLE
Fallback to HTTP 1.1 

### ISSUE THREAD

**Issue by Globegitter** [nghttp2/nghttp2#314]
Just playing around with nghttp2 and love the fact to already have an HTTP/2 compliant server for python.

Just following the basic examples, https://nghttp2.org/documentation/python-apiref.html#http-2-servers when I make a request in Safari 8 (which does not support HTTP/2) the server throws an exception and the request fails:

```
ERROR:asyncio:Exception in callback _HTTP2Session.connection_made(<_SelectorSsl...e, bufsize=0>>)
handle: <Handle _HTTP2Session.connection_made(<_SelectorSsl...e, bufsize=0>>)>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "nghttp2.pyx", line 1271, in nghttp2._HTTP2Session.connection_made (nghttp2.c:18892)
AttributeError: 'NoneType' object has no attribute 'encode'
Traceback (most recent call last):
  File "nghttp2.pyx", line 1293, in nghttp2._HTTP2Session.data_received (nghttp2.c:19508)
AttributeError: 'NoneType' object has no attribute 'data_received'
ERROR:asyncio:Exception in callback _HTTP2Session.connection_made(<_SelectorSsl...e, bufsize=0>>)
handle: <Handle _HTTP2Session.connection_made(<_SelectorSsl...e, bufsize=0>>)>
Traceback (most recent call last):
```

Is there any way to automatically fall back to HTTP 1/1.1 if the browser/client does not support HTTP/2? Or at least check manually and then serve the content with HTTP 1.1?

**Comment by tatsuhiro-t** [comment]
Currently there is no HTTP/1 implementation in Python code.
If python standard lib has asyncio based HTTP/1 implementation, we can use it as fallback, but we don't have one.
Perhaps, we can implement HTTP/1 using third-paty/http-parser.
