### ISSUE TITLE
nghttpx crash if backend refuse connection

### ISSUE THREAD

**Issue by fcicq** [nghttp2/nghttp2#565]
version: git master 5974abad757a06a50e07625db3fdaa6192cfe86c
OS: ubuntu 16.04, gcc version 5.3.1 20160323 (Ubuntu 5.3.1-13ubuntu1)
command line:
~/nghttp2/src/nghttpx -b "127.0.0.1,8444;/;proto=h2" -f "127.0.0.1,8118;no-tls" --no-via --backend-connections-per-host=32 --backend-http2-window-bits=19 --backend-http2-connection-window-bits=19 --backend-read-timeout=20 --backend-connections-per-host=64

Note: the frontend is http1.1 and the backend is unencrypted h2c. but if I restart or close the backend service, nghttpx will crash after the connection failure.

log:
02/Apr/2016:21:05:14 +0800 PID12661 [WARN] shrpx_connect_blocker.cc:63 Could not connect 1 times in a row; sleep for 1 seconds
02/Apr/2016:21:06:08 +0800 PID12661 [NOTICE] Worker process: [12675] exited abnormally with status b; exit status 0; signal Segmentation fault(11)
02/Apr/2016:21:06:08 +0800 PID12661 [NOTICE] Shutdown momentarily

gdb trace:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007fe30e6bde68 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007fe30e6bde68 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x000000000045e13e in shrpx::RateLimit::handle_tls_pending_read (this=0x7fe30e6bdd70) at shrpx_rate_limit.cc:108
#2  0x00000000004427b6 in shrpx::HttpsUpstream::on_read (this=0x244adf0) at shrpx_https_upstream.cc:596
#3  0x0000000000472196 in shrpx::ClientHandler::upstream_read (this=<optimized out>) at shrpx_client_handler.cc:299
#4  0x0000000000472992 in std::function<int (shrpx::ClientHandler&)>::operator()(shrpx::ClientHandler&) const (__args#0=..., this=0x2450808)
    at /usr/include/c++/5/functional:2267
#5  shrpx::ClientHandler::on_read (this=this@entry=0x2450490) at shrpx_client_handler.cc:635
#6  0x000000000047490b in shrpx::ClientHandler::upstream_http1_connhd_read (this=0x2450490) at shrpx_client_handler.cc:383
#7  0x0000000000472992 in std::function<int (shrpx::ClientHandler&)>::operator()(shrpx::ClientHandler&) const (__args#0=..., this=0x2450808)
    at /usr/include/c++/5/functional:2267
#8  shrpx::ClientHandler::on_read (this=this@entry=0x2450490) at shrpx_client_handler.cc:635
#9  0x0000000000472a54 in shrpx::ClientHandler::read_clear (this=0x2450490) at shrpx_client_handler.cc:118
#10 0x00000000004727e6 in std::function<int (shrpx::ClientHandler&)>::operator()(shrpx::ClientHandler&) const (__args#0=..., this=0x24507c8)
    at /usr/include/c++/5/functional:2267
#11 shrpx::ClientHandler::do_read (this=0x2450490) at shrpx_client_handler.cc:631
#12 shrpx::(anonymous namespace)::readcb (loop=<optimized out>, w=<optimized out>, revents=<optimized out>) at shrpx_client_handler.cc:91
#13 0x00007fe30fa4bd73 in ev_invoke_pending () from /usr/lib/x86_64-linux-gnu/libev.so.4
#14 0x00007fe30fa4f3de in ev_run () from /usr/lib/x86_64-linux-gnu/libev.so.4
#15 0x0000000000465712 in shrpx::worker_process_event_loop (wpconf=wpconf@entry=0x7ffe2e015b60) at shrpx_worker_process.cc:531
#16 0x0000000000412576 in shrpx::(anonymous namespace)::fork_worker_process (ssv=0x7ffe2e015bb0) at shrpx.cc:888
#17 shrpx::(anonymous namespace)::event_loop () at shrpx.cc:974
#18 0x000000000040b6e4 in shrpx::main (argc=11, argv=0x7ffe2e017bb8) at shrpx.cc:3108
#19 0x00000000004166b2 in std::function<int (int, char**)>::operator()(int, char**) const (__args#1=0x7ffe2e017bb8, __args#0=11, this=0x7ffe2e017a70)
---Type <return> to continue, or q <return> to quit---
    at /usr/include/c++/5/functional:2267
#20 nghttp2::run_app(std::function<int (int, char**)>, int, char**) (app=..., argc=<optimized out>, argv=<optimized out>) at template.h:538
#21 0x0000000000409cdc in main (argc=<optimized out>, argv=<optimized out>) at shrpx.cc:3121
```

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this issue.
Looks like the backtrace  is unrelated another crash log to the Segmentation fault in log.

**Comment by tatsuhiro-t** [comment]
Or, there is concurrent connections going on.  Is that your case?

**Comment by tatsuhiro-t** [comment]
OK, I got the nghttpx crash, looks like the location is different, but memory related bug shows something like this.  Looking into it.

**Comment by tatsuhiro-t** [comment]
I think b1662a3 fixes this bug.  Could you verify that it fixes this issue?

**Comment by fcicq** [comment]
Thankfully the issue can be reproduced \^o^/. will test soon. I guess older nghttp2 versions are also affected...

I have another issue with nghttpx and will open another issue to report later, I dont have enough time to collect the information :(.

**Comment by tatsuhiro-t** [comment]
Thank you.  Will release new version once the fix is verified.

**Comment by fcicq** [comment]
```
02/Apr/2016:23:28:47 +0800 PID23061 [WARN] shrpx_connect_blocker.cc:63 Could not connect 1 times in a row; sleep for 0 seconds
02/Apr/2016:23:28:48 +0800 PID23061 [WARN] shrpx_connect_blocker.cc:63 Could not connect 2 times in a row; sleep for 2 seconds
02/Apr/2016:23:28:50 +0800 PID23061 [WARN] shrpx_connect_blocker.cc:63 Could not connect 3 times in a row; sleep for 6 seconds
02/Apr/2016:23:28:56 +0800 PID23061 [WARN] shrpx_connect_blocker.cc:63 Could not connect 4 times in a row; sleep for 7 seconds
02/Apr/2016:23:29:05 +0800 PID23061 [WARN] shrpx_connect_blocker.cc:63 Could not connect 5 times in a row; sleep for 23 seconds
```

looks good.

**Comment by fcicq** [comment]
the so-called "another issue" is now invalidated. so no more issues now. thanks for fixing the bug! have a nice day :+1:
