### ISSUE TITLE
Another coredump when using asio library

### ISSUE THREAD

**Issue by wangruowr** [nghttp2/nghttp2#706]
Hi,

We run into a new core when using the nghttp 1.11.1 at deflate_nv when setting a timeout.
stack trace is list below,

```
#0  0x000000000094b91c in deflate_nv (deflater=0x906f18, bufs=0x7f4da75fd3e0, nv=0x7f4da75fd520) at nghttp2_hd.c:1389
#1  0x0000000000903900 in nghttp2::defer<void (&)(nghttp2_session_callbacks*), nghttp2_session_callbacks*&> (f=@0x7f4db8014010) at template.h:91
#2  0x00000000008fd697 in std::allocator_traits<std::allocator<nghttp2::asio_http2::client::session_tcp_impl> >::construct<nghttp2::asio_http2::client::session_tcp_impl, boost::asio::io_service&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::posix_time::seconds> (__a=..., __p=0x0) at /usr/local/gcc-4.9.2/include/c++/4.9.2/bits/alloc_traits.h:399
#3  0x00000000008aac54 in logagent::H2Session::<lambda()>::operator()(void) const (__closure=0x7f4db8013290) at /home/qiwei.wqw/sambashare/Agent/src/h2csender/H2cSession.cpp:558
#4  0x00000000008b10a2 in std::set<void*, std::less<void*>, std::allocator<void*> >::clear (this=0x7f4da75fdac0) at /usr/local/gcc-4.9.2/include/c++/4.9.2/bits/stl_set.h:669
#5  0x00000000008b0d95 in boost::date_time::time_duration<boost::posix_time::time_duration, boost::date_time::time_resolution_traits<boost::date_time::time_resolution_traits_adapted64_impl, (boost::date_time::time_resolutions)5, 1000000l, 6u, int> >::fractional_seconds (this=0x8b0d95) at /home/qiwei.wqw/sambashare/Agent/include/boost/date_time/time_duration.hpp:132
#6  0x00000000008b06c0 in boost::date_time::date<boost::gregorian::date, boost::gregorian::gregorian_calendar, boost::gregorian::date_duration>::year_month_day (this=0x7f499bffeb90)
    at /home/qiwei.wqw/sambashare/Agent/include/boost/date_time/date.hpp:99
```

![image](https://cloud.githubusercontent.com/assets/19812589/19269054/b2538616-8fea-11e6-9f43-0b1af9d53a67.png)

with detail 
```
#0  0x000000000094b91c in deflate_nv (deflater=0x906f18, bufs=0x7f4da75fd3e0, nv=0x7f4da75fd520) at nghttp2_hd.c:1389
        rv = 32589
        res = {index = 139971497285248, name_value_match = 32 ' '}
        idx = 0
        indexing_mode = 0
        token = 0
        mem = 0x7f4da75fd680
        hash = 2808075504
```

is it a known issue? or get fixed at later releases?

Thanks,
Baron

**Comment by tatsuhiro-t** [comment]
This is not a known issue, but stack trace is very strange.  The detailed log above shows completely broken stack.
Are you compiled and installed libnghttp2 and libnghttp2_asio correctly?
Is there any possibility of data race or breakage because of multi threads?

**Comment by wangruowr** [comment]
Sure, we also think it is a wrong FBT, please have it closed and I will turn to you when getting more info.
Thanks for your time!
