### ISSUE TITLE
Crash in tiny-nghttpd

### ISSUE THREAD

**Issue by robertswiecki** [nghttp2/nghttp2#744]
Hi,

I'm getting a crash (out of bounds heap write) with tiny-nghttp2. I think it might be rather the tool than the library, but I'm not familiar with the nghttp2 code, so please take a look. Repro (net input) attached.

```
TIME: 2016-12-14.14:47:12
FUZZER ARGS:
 flipRate     : 0.001000
 externalCmd  : NULL
 fuzzStdin    : FALSE
 timeout      : 1 (sec)
 ignoreAddr   : (nil)
 memoryLimit  : 0 (MiB)
 targetPid    : 0
 targetCmd    : (null)
 wordlistFile : ./httpd.wordlist
 dynFileMethod: 
 fuzzTarget   : ./tiny-nghttpd 127.0.0.1 8080 /usr/bin/ 
ORIG_FNAME: TIME.20161209.083509.ITER.297192380.RND.17cddb3bdf9bc811.HONGGFUZZ.COV
FUZZ_FNAME: ./SIGABRT.PC.7ffff6480c37.STACK.180481e62.CODE.-6.ADDR.(nil).INSTR.cmp____$0xfffffffffffff000,%rax.fuzz
PID: 13001
SIGNAL: SIGABRT (6)
FAULT ADDRESS: (nil)
INSTRUCTION: cmp____$0xfffffffffffff000,%rax
STACK HASH: 0000000180481e62
STACK:
 <0x00007ffff6484028> [[UNKNOWN]():0 at /lib/x86_64-linux-gnu/libc-2.19.so]
 <0x000000000050552b> [_ZN11__sanitizer5AbortEv():0 at /usr/local/fuzz/home/fuzz/fuzz/apache/tiny-nghttpd]
 <0x00000000004ff37a> [_ZN11__sanitizer3DieEv():0 at /usr/local/fuzz/home/fuzz/fuzz/apache/tiny-nghttpd]
 <0x00000000004e7bb5> [_ZN6__asan18ReportGenericErrorEmmmmbmjb():0 at /usr/local/fuzz/home/fuzz/fuzz/apache/tiny-nghttpd]
 <0x000000000046aa64> [memcpy():0 at /usr/local/fuzz/home/fuzz/fuzz/apache/tiny-nghttpd]
 <0x000000000051acbd> [io_buf_add_str():189 at /usr/local/fuzz/home/fuzz/fuzz/apache/tiny-nghttpd]
 <0x0000000000514a7c> [on_header_callback():1056 at /usr/local/fuzz/home/fuzz/fuzz/apache/tiny-nghttpd]
 <0x000000000052fe10> [session_call_on_header():3333 at /usr/local/fuzz/home/fuzz/fuzz/apache/tiny-nghttpd]
 <0x000000000052b072> [inflate_header_block():3663 at /usr/local/fuzz/home/fuzz/fuzz/apache/tiny-nghttpd]
 <0x0000000000528fbe> [nghttp2_session_mem_recv():6048 at /usr/local/fuzz/home/fuzz/fuzz/apache/tiny-nghttpd]
 <0x0000000000518500> [do_read():1156 at /usr/local/fuzz/home/fuzz/fuzz/apache/tiny-nghttpd]
 <0x0000000000517c23> [handle_connection():1232 at /usr/local/fuzz/home/fuzz/fuzz/apache/tiny-nghttpd]
 <0x000000000051619d> [io_loop_run():598 at /usr/local/fuzz/home/fuzz/fuzz/apache/tiny-nghttpd]
 <0x0000000000512e64> [main():1467 at /usr/local/fuzz/home/fuzz/fuzz/apache/tiny-nghttpd]
 <0x00007ffff646bf45> [[UNKNOWN]():0 at /lib/x86_64-linux-gnu/libc-2.19.so]
 <0x000000000041b231> [_start():0 at /usr/local/fuzz/home/fuzz/fuzz/apache/tiny-nghttpd]
 <0x0000000000000000> [[UNKNOWN]():0 at UNKNOWN]
```

```
Stack-trace.
==13004==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6210001c45a0 at pc 0x00000046aa37 bp 0x7fffffff1f10 sp 0x7fffffff16c0
WRITE of size 8190 at 0x6210001c45a0 thread T0
    #0 0x46aa36 in memcpy (/usr/local/fuzz/home/fuzz/fuzz/apache/tiny-nghttpd+0x46aa36)
    #1 0x51acbc in io_buf_add_str /usr/local/fuzz/home/fuzz/fuzz/apache/nghttp2-1.17.0/examples/tiny-nghttpd.c:188:3
    #2 0x514a7b in on_header_callback /usr/local/fuzz/home/fuzz/fuzz/apache/nghttp2-1.17.0/examples/tiny-nghttpd.c:1056:18
    #3 0x52fe0f in session_call_on_header /proc/self/cwd/third_party/nghttp2/lib/nghttp2_session.c:3333:10
    #4 0x52b071 in inflate_header_block /proc/self/cwd/third_party/nghttp2/lib/nghttp2_session.c:3663:14
    #5 0x528fbd in nghttp2_session_mem_recv /proc/self/cwd/third_party/nghttp2/lib/nghttp2_session.c:6049:13
    #6 0x5184ff in do_read /usr/local/fuzz/home/fuzz/fuzz/apache/nghttp2-1.17.0/examples/tiny-nghttpd.c:1156:13
    #7 0x517c22 in handle_connection /usr/local/fuzz/home/fuzz/fuzz/apache/nghttp2-1.17.0/examples/tiny-nghttpd.c:1232:10
    #8 0x51619c in io_loop_run /usr/local/fuzz/home/fuzz/fuzz/apache/nghttp2-1.17.0/examples/tiny-nghttpd.c:598:7
    #9 0x512e63 in main /usr/local/fuzz/home/fuzz/fuzz/apache/nghttp2-1.17.0/examples/tiny-nghttpd.c:1465:3
    #10 0x7ffff646bf44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287
    #11 0x41b230 in _start (/usr/local/fuzz/home/fuzz/fuzz/apache/tiny-nghttpd+0x41b230)

0x6210001c45a0 is located 0 bytes to the right of 4256-byte region [0x6210001c3500,0x6210001c45a0)
allocated by thread T0 here:
    #0 0x4de1a6 in malloc (/usr/local/fuzz/home/fuzz/fuzz/apache/tiny-nghttpd+0x4de1a6)
    #1 0x51a018 in stream_new /usr/local/fuzz/home/fuzz/fuzz/apache/nghttp2-1.17.0/examples/tiny-nghttpd.c:362:10
    #2 0x5141d4 in on_begin_headers_callback /usr/local/fuzz/home/fuzz/fuzz/apache/nghttp2-1.17.0/examples/tiny-nghttpd.c:1002:10
    #3 0x525a56 in session_call_on_begin_headers /proc/self/cwd/third_party/nghttp2/lib/nghttp2_session.c:3313:10
    #4 0x525834 in nghttp2_session_on_request_headers_received /proc/self/cwd/third_party/nghttp2/lib/nghttp2_session.c:3887:8
    #5 0x52a81d in session_process_headers_frame /proc/self/cwd/third_party/nghttp2/lib/nghttp2_session.c:4032:12
    #6 0x5289e0 in nghttp2_session_mem_recv /proc/self/cwd/third_party/nghttp2/lib/nghttp2_session.c:5840:14
    #7 0x5184ff in do_read /usr/local/fuzz/home/fuzz/fuzz/apache/nghttp2-1.17.0/examples/tiny-nghttpd.c:1156:13
    #8 0x517c22 in handle_connection /usr/local/fuzz/home/fuzz/fuzz/apache/nghttp2-1.17.0/examples/tiny-nghttpd.c:1232:10
    #9 0x51619c in io_loop_run /usr/local/fuzz/home/fuzz/fuzz/apache/nghttp2-1.17.0/examples/tiny-nghttpd.c:598:7
    #10 0x512e63 in main /usr/local/fuzz/home/fuzz/fuzz/apache/nghttp2-1.17.0/examples/tiny-nghttpd.c:1465:3
    #11 0x7ffff646bf44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287

SUMMARY: AddressSanitizer: heap-buffer-overflow (/usr/local/fuzz/home/fuzz/fuzz/apache/tiny-nghttpd+0x46aa36) in memcpy
Shadow bytes around the buggy address:
  0x0c4280030860: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4280030870: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4280030880: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4280030890: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c42800308a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c42800308b0: 00 00 00 00[fa]fa fa fa fa fa fa fa fa fa fa fa
  0x0c42800308c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c42800308d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c42800308e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c42800308f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4280030900: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==13004==ABORTING
```

[SIGABRT.PC.7ffff6480c37.STACK.180481e62.CODE.-6.ADDR.(nil).INSTR.cmp____$0xfffffffffffff000,%rax.txt](https://github.com/nghttp2/nghttp2/files/651887/SIGABRT.PC.7ffff6480c37.STACK.180481e62.CODE.-6.ADDR.nil.INSTR.cmp____.0xfffffffffffff000.rax.txt)

**Comment by tatsuhiro-t** [comment]
Thank you for telling us.
It looks like tiny-nghttpd lacks lots of boundary check.
We'd like to drop this example program rather than fixing it since currently doing it does not add no value for the project.  nghttpd does the better job in this area.

**Comment by robertswiecki** [comment]
Thanks, is there any way to make nghttpd to accept HTTP/2 w/o SSL/TLS? It'd greately help me with fuzzing of this protocol. Currently I'm using Apache+mod_httpd2 and Protocol h2c

**Comment by tatsuhiro-t** [comment]
Yes.  --no-tls option does the job.

**Comment by robertswiecki** [comment]
Thanks
